apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app"
spec:
  selector:
    matchLabels:
      app: "app"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "app"
        env:
          - name: DB_HOSTNAME
            value: {{ .Values.dbhost }}
          - name: DB_USERNAME
            value: testuser
          - name: DB_PASSWORD
            value: TestPass
          - name: DB_NAME 
            value: servian
        ports:
        - containerPort: 3000